//! Lexer differential test: replays token streams dumped from the real
//! org.apache.commons.jexl3.parser.ParserTokenManager (tests/data/lexer, generated by
//! tools/gen_lexer_cases.py + oracle `tokens` mode) and compares every token and lexical error.
mod common;
use common::json::{self, Json};
use rust_jexl3::parser::parser_token_manager::ParserTokenManager;
use rust_jexl3::parser::simple_char_stream::SimpleCharStream;

fn lex(src: &[u16], registers: bool) -> Json {
    let mut tm = ParserTokenManager::new(SimpleCharStream::new(src));
    if registers {
        tm.default_lex_state = 2;
        tm.switch_to(2).unwrap();
    }
    let mut out = Vec::new();
    loop {
        match tm.get_next_token() {
            Ok(t) => {
                let eof = t.kind == 0;
                out.push(Json::Arr(vec![
                    Json::Num(t.kind.to_string()),
                    Json::Str(t.image.clone()),
                    Json::Num(t.begin_line.to_string()),
                    Json::Num(t.begin_column.to_string()),
                    Json::Num(t.end_line.to_string()),
                    Json::Num(t.end_column.to_string()),
                ]));
                if eof {
                    break;
                }
            }
            Err(e) => {
                out.push(Json::Obj(vec![
                    ("msg".into(), Json::Str(e.get_message())),
                    ("line".into(), Json::Num(e.get_line().to_string())),
                    ("column".into(), Json::Num(e.get_column().to_string())),
                    ("after".into(), Json::Str(e.get_after().to_vec())),
                ]));
                break;
            }
        }
    }
    Json::Arr(out)
}

#[test]
fn lexer_matches_oracle() {
    // LEXER_CASES / LEXER_EXPECTED point at a larger local campaign (see PROGRESS.md)
    let cp = std::env::var("LEXER_CASES").unwrap_or_else(|_| "tests/data/lexer/cases.jsonl".into());
    let ep = std::env::var("LEXER_EXPECTED").unwrap_or_else(|_| "tests/data/lexer/expected.jsonl".into());
    let cases = std::fs::read_to_string(cp).unwrap();
    let expected = std::fs::read_to_string(ep).unwrap();
    let mut failures = Vec::new();
    let mut n = 0;
    for (c, e) in cases.lines().zip(expected.lines()) {
        let c = json::parse(c).unwrap();
        let e = json::parse(e).unwrap();
        let src = c.get("src").unwrap().str16().unwrap();
        let registers = c.get("registers").and_then(Json::as_bool).unwrap_or(false);
        let got = lex(src, registers);
        let want = e.get("tokens").unwrap();
        n += 1;
        if &got != want {
            failures.push(format!(
                "{}: src={:?}\n  want {}\n  got  {}",
                c.get("id").unwrap().string().unwrap(),
                String::from_utf16_lossy(src),
                json::to_string(want),
                json::to_string(&got)
            ));
        }
    }
    assert!(n > 0);
    assert!(failures.is_empty(), "{} of {} lexer cases differ:\n{}", failures.len(), n, failures.iter().take(10).cloned().collect::<Vec<_>>().join("\n"));
}
