//! JDK-shim differential test: every method, property, iteration and constructor the shim models,
//! replayed against the real `JexlEngine.invokeMethod` / `getProperty` / `setProperty` /
//! `newInstance` / `getUberspect().getIterator()` of commons-jexl3-3.2.1.
//!
//! The fixture is generated by `tools/gen_spi_cases.py`; see PROGRESS.md for the campaign command.
mod common;

use common::decode::decode;
use common::json::{self, Json};
use rust_jexl::introspection::jdk_shim::{ClassValue, JdkShim};
use rust_jexl::introspection::{JexlUberspect, PropertyResolver, ResolverStrategy};
use rust_jexl::jexl_arithmetic::JexlArithmetic;
use rust_jexl::jexl_exception::JexlException;
use rust_jexl::jexl_operator::JexlOperator;
use rust_jexl::value::Value;

// ------------------------------------------------------------------ encoding (mirrors Oracle.encode)

fn typed(t: &str, v: Option<Json>) -> Json {
    let mut kv = vec![("t".to_string(), Json::str(t))];
    if let Some(v) = v {
        kv.push(("v".to_string(), v));
    }
    Json::Obj(kv)
}

fn with(mut o: Json, key: &str, v: Json) -> Json {
    if let Json::Obj(kv) = &mut o {
        kv.push((key.to_string(), v));
    }
    o
}

/// Oracle.className: JEXL classes are reported relative to their package.
fn class_name(v: &Value) -> String {
    let n = v.class_name();
    match n.strip_prefix("org.apache.commons.jexl3.") {
        Some(rest) => rest.to_string(),
        None => n,
    }
}

fn encode(v: &Value) -> Json {
    match v {
        Value::Array(a) => with(
            typed("Array", Some(Json::Arr(a.snapshot().iter().map(encode).collect()))),
            "c",
            Json::str(&a.component.simple_name()),
        ),
        Value::List(l) => with(
            typed("List", Some(Json::Arr(l.snapshot().iter().map(encode).collect()))),
            "c",
            Json::str(&v.class_name()),
        ),
        Value::Set(s) => with(
            typed("Set", Some(Json::Arr(s.snapshot().iter().map(encode).collect()))),
            "c",
            Json::str(&v.class_name()),
        ),
        Value::Object(_) => {
            if let Some(c) = v.as_host::<ClassValue>() {
                return typed("Class", Some(Json::str(&c.name)));
            }
            let o = with(typed("Object", None), "c", Json::str(&class_name(v)));
            if v.has_identity_to_string() || v.class_name().contains("Iterator") || v.class_name().ends_with("$Itr") {
                with(o, "nd", Json::Bool(true))
            } else {
                with(o, "v", Json::Str(v.java_to_jstring().units().to_vec()))
            }
        }
        Value::Map(m) => with(
            typed(
                "Map",
                Some(Json::Arr(
                    m.snapshot().iter().map(|(k, val)| Json::Arr(vec![encode(k), encode(val)])).collect(),
                )),
            ),
            "c",
            Json::str(&v.class_name()),
        ),
        other => common::encode::encode(other),
    }
}

/// The exception shape the oracle writes for a throw.
fn error(e: &JexlException) -> Json {
    let mut kv = vec![
        ("class".to_string(), Json::str(&e.class_name())),
        (
            "msg".to_string(),
            match e.get_message() {
                Some(m) => Json::Str(m.units().to_vec()),
                None => Json::Null,
            },
        ),
    ];
    if let Some(c) = e.get_cause() {
        kv.push((
            "cause".to_string(),
            Json::Obj(vec![
                ("class".to_string(), Json::str(&c.class_name())),
                (
                    "msg".to_string(),
                    match c.get_message() {
                        Some(m) => Json::Str(m.units().to_vec()),
                        None => Json::Null,
                    },
                ),
            ]),
        ));
    }
    Json::Obj(kv)
}

// ------------------------------------------------------------------ the engine entry points

/// port of: Engine.invokeMethod (uberspect.getMethod + the narrowArguments retry)
fn invoke_method(shim: &JdkShim, obj: &Value, name: &str, args: &[Value]) -> Result<Value, JexlException> {
    if obj.is_null() {
        // Java reaches obj.getClass() inside MethodExecutor.discover
        return Err(JexlException::method_info(
            None,
            name,
            Some(args),
            Some(JexlException::java(
                "java.lang.NullPointerException",
                Some("Cannot invoke \"Object.getClass()\" because \"obj\" is null".into()),
            )),
        ));
    }
    let arith = JexlArithmetic::new(true, None, i32::MIN);
    let mut args = args.to_vec();
    let mut method = shim.get_method(obj, name, &args);
    if method.is_none() && arith.narrow_arguments(&mut args) {
        method = shim.get_method(obj, name, &args);
    }
    // Java packs a lone trailing vararg into the caller's array, so the failure message below
    // reports the packed signature
    shim.pack_varargs(obj, name, &mut args);
    match method {
        Some(m) => m.invoke(obj, &args).map_err(|e| {
            if e.is_jexl() {
                e
            } else {
                JexlException::method_info(None, name, Some(&args), Some(e))
            }
        }),
        None => Err(JexlException::method_info(None, name, Some(&args), None)),
    }
}

/// port of: Engine.newInstance(String, Object...)
fn new_instance(shim: &JdkShim, name: &str, args: &[Value]) -> Result<Value, JexlException> {
    let arith = JexlArithmetic::new(true, None, i32::MIN);
    let handle = Value::string(name);
    let mut args = args.to_vec();
    let mut ctor = shim.get_constructor(&handle, &args);
    if ctor.is_none() && arith.narrow_arguments(&mut args) {
        ctor = shim.get_constructor(&handle, &args);
    }
    match ctor {
        Some(c) => c.invoke(&handle, &args).map_err(|e| {
            if e.is_jexl() {
                e
            } else {
                JexlException::method_info(None, name, Some(&args), Some(e))
            }
        }),
        None => Err(JexlException::method_info(None, name, Some(&args), None)),
    }
}

/// port of: InterpreterBase.getAttribute, as Engine.getProperty reaches it
fn get_property(shim: &JdkShim, obj: &Value, ident: &Value, array: bool) -> Result<Value, JexlException> {
    let op = if array { JexlOperator::ArrayGet } else { JexlOperator::PropertyGet };
    let resolvers: &[PropertyResolver] = shim.get_resolvers(Some(op), obj);
    let mut cause = None;
    if let Some(g) = shim.get_property_get_with(resolvers, obj, ident) {
        match g.invoke(obj) {
            Ok(v) => return Ok(v),
            Err(e) => cause = Some(e),
        }
    }
    Err(JexlException::property(None, &ident.java_to_string(), true, cause))
}

/// port of: InterpreterBase.setAttribute, as Engine.setProperty reaches it
fn set_property(shim: &JdkShim, obj: &Value, ident: &Value, value: &Value, array: bool) -> Result<(), JexlException> {
    let op = if array { JexlOperator::ArraySet } else { JexlOperator::PropertySet };
    let resolvers: &[PropertyResolver] = shim.get_resolvers(Some(op), obj);
    let mut setter = shim.get_property_set_with(resolvers, obj, ident, value);
    if setter.is_none() {
        let arith = JexlArithmetic::new(true, None, i32::MIN);
        let mut narrow = [value.clone()];
        if arith.narrow_arguments(&mut narrow) {
            setter = shim.get_property_set_with(resolvers, obj, ident, &narrow[0]);
        }
    }
    let mut cause = None;
    if let Some(s) = setter {
        match s.invoke(obj, value) {
            Ok(_) => return Ok(()),
            Err(e) => cause = Some(e),
        }
    }
    Err(JexlException::property(None, &ident.java_to_string(), true, cause))
}

// ------------------------------------------------------------------ case running

/// `name` as the engine parses it: `#0.<name>` or `#0[<name>]`.
fn identifier(name: &str) -> (Value, bool) {
    if let Some(inner) = name.strip_prefix('[').and_then(|s| s.strip_suffix(']')) {
        if let Some(q) = inner.strip_prefix('\'').and_then(|s| s.strip_suffix('\'')) {
            return (Value::string(q), true);
        }
        return (Value::Integer(inner.parse().expect("index")), true);
    }
    if !name.is_empty() && name.bytes().all(|b| b.is_ascii_digit()) {
        return (Value::Integer(name.parse().expect("index")), false);
    }
    (Value::string(name), false)
}

fn run(case: &Json) -> Json {
    let shim = JdkShim::new(ResolverStrategy::Jexl);
    let op = case.get("op").and_then(Json::string).expect("op");
    let name = case.get("name").and_then(Json::string).unwrap_or_default();
    let target = case.get("target").map(decode).unwrap_or(Value::Null);
    let args: Vec<Value> = case.get("args").and_then(Json::arr).unwrap_or(&[]).iter().map(decode).collect();
    let outcome: Result<Json, JexlException> = match op.as_str() {
        "invoke" => invoke_method(&shim, &target, &name, &args).map(|v| encode(&v)),
        "construct" => new_instance(&shim, &name, &args).map(|v| encode(&v)),
        "get" => {
            let (ident, array) = identifier(&name);
            get_property(&shim, &target, &ident, array).map(|v| encode(&v))
        }
        "set" => {
            let (ident, array) = identifier(&name);
            set_property(&shim, &target, &ident, &args[0], array).map(|_| encode(&target))
        }
        "iterate" => {
            if target.is_null() {
                Err(JexlException::java(
                    "java.lang.NullPointerException",
                    Some("Cannot invoke \"Object.getClass()\" because \"obj\" is null".into()),
                ))
            } else {
                match shim.get_iterator(&target) {
                    Some(it) => {
                        let values: Vec<Json> = it.take(64).map(|v| encode(&v)).collect();
                        Ok(Json::Obj(vec![("t".into(), Json::str("Iterated")), ("v".into(), Json::Arr(values))]))
                    }
                    None => Ok(encode(&Value::Null)),
                }
            }
        }
        other => panic!("unknown spi op {}", other),
    };
    match outcome {
        Ok(v) => v,
        Err(e) => Json::Obj(vec![("throw".into(), error(&e))]),
    }
}

/// Three things in the oracle's output are not reproducible and are masked here:
///  * the JexlInfo a JEXL exception carries is the oracle's own stack frame (`JexlInfo()` reads
///    `new Throwable().getStackTrace()`), so only the message body is comparable;
///  * identity hashes (`[I@1a2b3c`);
///  * the messages the VM builds lazily for a NullPointerException ("helpful NPE") and for the
///    implicit checkcast's ClassCastException: once the throwing frame is JIT-compiled the VM
///    takes its fast-throw path and the message is null, so the same case yields the detailed
///    text on the first runs and nothing afterwards. Only the exception class is compared there.
fn normalize(v: &Json, in_msg: bool) -> Json {
    match v {
        Json::Str(s) => {
            let mut text = String::from_utf16_lossy(s);
            if in_msg {
                if let Some(p) = text.find(' ') {
                    text = format!("<info>{}", &text[p..]);
                }
            }
            if !text.contains('@') {
                return Json::Str(text.encode_utf16().collect());
            }
            let mut out = String::new();
            let mut it = text.chars().peekable();
            while let Some(c) = it.next() {
                out.push(c);
                if c == '@' {
                    let mut n = 0;
                    while it.peek().map(|c| c.is_ascii_hexdigit()).unwrap_or(false) {
                        it.next();
                        n += 1;
                    }
                    if n > 0 {
                        out.push_str("ID");
                    }
                }
            }
            Json::Str(out.encode_utf16().collect())
        }
        Json::Arr(a) => Json::Arr(a.iter().map(|x| normalize(x, false)).collect()),
        Json::Obj(kv) => {
            let class = match kv.iter().find(|(n, _)| n == "class") {
                Some((_, Json::Str(c))) => String::from_utf16_lossy(c),
                _ => String::new(),
            };
            if class == "java.lang.NullPointerException" || class == "java.lang.ClassCastException" {
                return Json::Obj(vec![
                    ("class".to_string(), Json::str(&class)),
                    ("msg".to_string(), Json::str("<vm-lazy-message>")),
                ]);
            }
            Json::Obj(
                kv.iter()
                    .map(|(k, x)| (k.clone(), normalize(x, k == "msg" && class.starts_with("JexlException"))))
                    .collect(),
            )
        }
        other => other.clone(),
    }
}

#[test]
fn jdk_shim_matches_oracle() {
    let cp = std::env::var("SPI_CASES").unwrap_or_else(|_| "tests/data/spi/cases.jsonl".into());
    let ep = std::env::var("SPI_EXPECTED").unwrap_or_else(|_| "tests/data/spi/expected.jsonl".into());
    let cases = std::fs::read_to_string(cp).expect("cases");
    let expected = std::fs::read_to_string(ep).expect("expected");
    let mut failures: Vec<String> = Vec::new();
    let mut n = 0usize;
    for (c, e) in cases.lines().zip(expected.lines()) {
        let case = json::parse(c).expect("case json");
        let outcome = json::parse(e).expect("expected json");
        let want = match outcome.get("result") {
            Some(w) => w.clone(),
            None => continue,
        };
        n += 1;
        let got = normalize(&run(&case), false);
        let want = normalize(&want, false);
        if got != want {
            if let Ok(path) = std::env::var("SPI_DUMP") {
                use std::io::Write;
                let mut f = std::fs::OpenOptions::new().create(true).append(true).open(path).expect("dump");
                let rec = Json::Obj(vec![
                    ("id".into(), case.get("id").cloned().unwrap_or(Json::Null)),
                    ("op".into(), case.get("op").cloned().unwrap_or(Json::Null)),
                    ("name".into(), case.get("name").cloned().unwrap_or(Json::Null)),
                    ("target".into(), case.get("target").cloned().unwrap_or(Json::Null)),
                    ("args".into(), case.get("args").cloned().unwrap_or(Json::Null)),
                    ("want".into(), want.clone()),
                    ("got".into(), got.clone()),
                ]);
                writeln!(f, "{}", json::to_string(&rec)).expect("write");
            }
            failures.push(format!(
                "{}: {} {} {}\n  target {}\n  want {}\n  got  {}",
                case.get("id").and_then(Json::string).unwrap_or_default(),
                case.get("op").and_then(Json::string).unwrap_or_default(),
                case.get("name").and_then(Json::string).unwrap_or_default(),
                case.get("args").map(json::to_string).unwrap_or_default(),
                case.get("target").map(json::to_string).unwrap_or_default(),
                json::to_string(&want),
                json::to_string(&got)
            ));
        }
    }
    assert!(n > 0, "no cases");
    assert!(
        failures.is_empty(),
        "{} of {} spi cases differ:\n{}",
        failures.len(),
        n,
        failures.iter().take(12).cloned().collect::<Vec<_>>().join("\n")
    );
}
